version: "2"
services:
### PHP + Apache2 ##########################################
  php:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
    container_name: ${PHP_CONTAUBER_NAME}  
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${DATA_LOG_PATH}/apache2:/var/log/apache2
      - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
      - ${APACHE_CONF}:/etc/apache2/apache2.conf
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
      - "${APACHE_HOST_HTTPS_PORT}:443"
    networks:
      - backend

### mysql ##################################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    container_name: ${MYSQL_CONTAUBER_NAME}  
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

### Redis ##################################################
  redis:
    build: ./redis
    container_name: ${REDIST_CONTAUBER_NAME}  
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
      
networks:
  backend: