version: "2"
services:
### PHP + Apache2 ##########################################
  php:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
    restart: always
    container_name: ${PHP_CONTAINER_NAME}  
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${DATA_LOG_PATH}/apache2:/var/log/apache2
      - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
      - ${APACHE_CONF}/apache2.conf:/etc/apache2/apache2.conf
      - ${APACHE_CONF}/ports.conf:/etc/apache2/ports.conf
      - ./php/supervisor:/etc/supervisor/conf.d
      - ./crontabs:/var/spool/cron/crontabs
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
      - "${APACHE_HOST_HTTPS_PORT}:443"
      - "${SUPERVISORD_PORT}:9001"
    networks:
      - backend

### mysql ##################################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    restart: always
    container_name: ${MYSQL_CONTAINER_NAME}  
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

### Redis ##################################################
  redis:
    build: ./redis
    restart: always
    container_name: ${REDIST_CONTAINER_NAME}  
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

### MSSQL ##################################################
  mssql:
    build:
      context: ./mssql
    restart: always
    container_name: ${MSSQL_CONTAINER_NAME}  
    environment:
      - SA_PASSWORD=${MSSQL_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - ${DATA_PATH_HOST}/mssql:/var/opt/mssql
    ports:
      - "${MSSQL_PORT}:1433"
    networks:
      - backend

networks:
  backend: 
    driver: bridge 
    ipam: 
      config: 
        - subnet: ${SEGMENT}
          gateway: ${GATWAY}