version: "2"
services:
  php:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ${APP_CODE_PATH_HOST}:/var/www/html
      # - ${PHP_INI}:/usr/local/etc/php/php.ini
      # - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
      # - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
      # - ${APACHE_CONF}:/etc/apache2/apache2.conf
    ports:
      - 9000:9000
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ${APP_CODE_PATH_HOST}:/var/www/html
      - ./nginx:/etc/nginx/conf.d
      - ./log/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - backend

  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${MYSQL_DATA_PATH_HOST}:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend
networks:
  backend: