version: "2"
services:
  php:
    build:
      context: ./php
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ${APP_CODE_PATH_HOST}:/var/www/html
    ports:
      - 9000:9000
    networks:
      - backend

### nginx ################################################
  nginx:
    build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_CONTAINER=php
          - PHP_UPSTREAM_PORT=9000
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    volumes: 
      - ${APP_CODE_PATH_HOST}:/var/www/html
      - ./nginx/sites:/etc/nginx/sites-available
      - ${DATA_LOG_PATH}/nginx:/var/log/nginx
    depends_on:
      - php
    networks:
      - backend

### mysql ################################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

### Redis ################################################
  redis:
    build: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

### MSSQL ##################################################
  mssql:
    build:
      context: ./mssql
    container_name: ${MSSQL_CONTAUBER_NAME}  
    environment:
      - SA_PASSWORD=${MSSQL_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - ${DATA_PATH_HOST}/mssql:/var/opt/mssql
    ports:
      - "${MSSQL_PORT}:1433"
    networks:
      - backend

networks:
  backend: